version: "2.1"
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    volumes:
      - /mnt/Data/docker/qbittorrent/config:/config
      - /mnt/Data/docker/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      #- 6881:6881
      #- 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
