version: '2.4'

services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: unless-stopped    
    volumes:
      - /mnt/Data/docker/octoprint:/octoprint
    ports:
      - 8084:80
    environment:
      - ENABLE_MJPG_STREAMER=true
    devices:
      -  /dev/ttyUSB0:/dev/ttyACM0
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/media0:/dev/media0
  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - PGID=0
  #    - TZ=America/Chicago
  #  volumes:
  #    - octoprint:/octoprint
