---
version: "3.3"
services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    ports:
      - 8084:3000
    volumes:
      - ${HOME}/data/homepage/config:/app/config
      - ${HOME}/data/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #environment:
      #PUID: 1000
      #PGID: 1000