version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 8084:3000
    volumes:
      - /home/${USER}/data/homepage/config:/app/config
      - /home/${USER}/data/homepage/icons:/app/public/icons
      #- /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
