---
version: "3.3"
services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 8084:3000
    volumes:
      - ${HOME}/data/homepage/config:/app/config
      - ${HOME}/data/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro