version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    command: hbbs -r 127.0.0.1:21117
    depends_on:
      - hbbr
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    volumes:
      - ${HOME}/data/rustdesk/data:/root
    networks:
      - rustdesk-net

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    command: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    volumes:
      - ${HOME}/data/rustdesk/data:/root
    networks:
      - rustdesk-net
