version: '3.3'
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    restart: unless-stopped
    hostname: orangepi3-lts
    network_mode: host
    privileged: true
    volumes:
      - ${HOME}/data/tailscale/varlib:/var/lib
      - ${HOME}/data/tailscale/nettun:/dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - TS_USERSPACE=true
      - TS_ROUTES=192.168.0.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
