---
version: "2.1"
services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8086:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    volumes:
      - ${HOME}/data/jellyfin/data:/app/data
      - ${HOME}/data/jellyfin/config:/config
      - ${HOME}/data/jellyfin/movies:/data/movies
      - ${HOME}/data/jellyfin/tvshows:/data/tvshows
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
