---
version: "2.1"
services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart: unless-stopped
    hostname: syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ${HOME}/data/syncthing/config:/config
      - ${HOME}/data/syncthing/data1:/data1
      - ${HOME}/data/syncthing/data2:/data2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
